source /pkgscripts/include/pkg_util.sh
package="webmin"
displayname="Webmin"
displayname_enu="Webmin"
displayname_ger="Webmin"
version="2.021"
firmware="7.0-40000"
os_min_ver="7.0-40000"
support_center="no"
thirdparty="yes"
reloadui="yes"
arch="noarch"
dsmuidir="ui"
ctl_stop="yes"
startable="yes"
silent_install="no"
silent_upgrade="yes"
silent_uninstall="no"
package_icon="PACKAGE_ICON.PNG"
package_icon_256="PACKAGE_ICON_256.PNG"
dsmappname="SYNO.SDS._ThirdParty.App.webmin"
maintainer="Akay-Devel"
description="Webmin is a web-based interface for system administration. Using any modern web browser, you can setup user accounts, Apache, DNS, file sharing and much more. Webmin removes the need to manually edit Unix configuration files like /etc/passwd, and lets you manage a system from the console or remotely."
description_enu="Webmin is a web-based interface for system administration. Using any modern web browser, you can setup user accounts, Apache, DNS, file sharing and much more. Webmin removes the need to manually edit Unix configuration files like /etc/passwd, and lets you manage a system from the console or remotely."
description_ger="Webmin ist eine Web-basierte Oberfläche für die Systemadministration. Mit jedem modernen Webbrowser können Sie Benutzerkonten, Apache, DNS, File Sharing und vieles mehr einrichten. Mit Webmin entfällt die Notwendigkeit, Unix Konfigurationsdateien wie z.B. /etc/passwd manuell zu bearbeiten und ermöglicht Ihnen die Verwaltung des Systems von der Konsole oder aus der Ferne."
helpurl="https://www.webmin.com"
[ "$(caller)" != "0 NULL" ] && return 0
pkg_dump_info
