#!/bin/sh
cd /var/packages/webmin/target/etc
./stop
/bin/sleep 1
if [ "${pkgwizard_remove_settings}" == "true" ]; then
	exit 0
elif [ "${pkgwizard_remove_settings}" == "false" ]; then
	exit 1
else
	exit 0
fi

exit 0

